### ISSUE TITLE
[Spec] Unknown messages are "extracted" from justifications?

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/cbc-beacon-chain#2]
eg. If a validator are at a state `{m1, m2}` and receive `m4` s.t. `m4 = (b, v {m1, m2 m3})` and `m3 = (b', v', {m1, m2})`, then can she move to a new state {m1, m2, m3, m4}` by *extracting* `m3` (because `m3` is compatible to her state)?.

It requires a message to keep all the signatures of messages it contains. (In the above case, `m3` should be validated by the signature of the sender.)

**Comment by yudetamago** [comment]
This is impossible (for now?) because justifications are a mapping from validator to latest message from the validator.
One possible solution is that if one of the message in justification is not justified in receiver's view, mark the message as `pending` and wait for the unreceived justification message.
